#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2 3
bspc monitor DisplayPort-1 -d 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9

bspc wm -O DisplayPort-0 DisplayPort-1 HDMI-A-0

bspc config border_width        1
bspc config window_gap          9

bspc config focused_border_color \#2aa198
bspc config normal_border_color \#93a1a1
bspc config active_border_color \#93a1a1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off

# Startup
killall picom
picom -b --experimental-backends &
feh --bg-fill /home/insti/Data/Pictures/Wallpaper/wallpaper.png &
$HOME/.config/polybar/launch.sh &
xmousepasteblock &
flameshot &
thunar -daemon &
fcitx5 &
dunst &
libinput-gestures &
nm-applet --indicator &
kdeconnect-indicator &
rclone --vfs-cache-mode writes mount "OneDrive":  ~/Data/OneDrive &

xsetwacom set 10 MapToOutput HDMI-A-0 
xsetwacom set 10 Area 0 0 15200 4008

xsetwacom set 12 Button 3 "key F17"
xsetwacom set 12 Button 1 "key F18"
xsetwacom set 12 Button 9 "key F19"
xsetwacom set 12 Button 8 "key F20"

# Startup apps
discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy --enable-blink-features=MiddleClickAutoscroll --start-minimized &
slack -u &
coolero &

sleep 5s
bspc wm -O DisplayPort-0 DisplayPort-1 HDMI-A-0