#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O DisplayPort-0 HDMI-A-0

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap          15

bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#404040
bspc config active_border_color \#909090

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Startup
killall picom
picom -b --experimental-backends &
feh --bg-fill $HOME/Pictures/wallpaper.jpg &
$HOME/.config/polybar/launch.sh &
xmousepasteblock &
fcitx5 &
dunst &
kdeconnect-indicator &
rclone --vfs-cache-mode writes mount "onedrive":  ~/OneDrive &

# Startup apps
discord --start-minimized &
slack -u &