#!/bin/sh

# /etc/libvirt/hooks/qemu

guest="$1"
command="$2"

if [ "$guest" = "win11" ]; then
   if [ "$command" = "started" ]; then
      systemctl set-property --runtime -- system.slice AllowedCPUs=0-3,8-11
      systemctl set-property --runtime -- user.slice AllowedCPUs=0-3,8-11
      systemctl set-property --runtime -- init.scope AllowedCPUs=0-3,8-11
   elif [ "$command" = "release" ]; then
      systemctl set-property --runtime -- system.slice AllowedCPUs=0-15
      systemctl set-property --runtime -- user.slice AllowedCPUs=0-15
      systemctl set-property --runtime -- init.scope AllowedCPUs=0-15
   fi
fi